'use client'

import AuthOptionProvider from '@/context/AuthContext'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Provider from '@/components/Provider'

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin']
})

//export const metadata: Metadata = {
//  title: 'Create Next App',
//  description: 'Generated by create next app'
//}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <AuthOptionProvider>
          <body className={poppins.className}>{children}</body>
        </AuthOptionProvider>
      </Provider>
    </html>
  )
}
